# Generated by Django 3.0.7 on 2020-08-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_auto_20200818_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='order',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name="'order-md-first' or 'order-md-last' *"),
        ),
    ]
