# Generated by Django 3.0.7 on 2020-08-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_auto_20200818_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='divider',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name="Add 'workshop-divider' unless it's the last one on the page *"),
        ),
    ]
