# Generated by Django 3.0.7 on 2020-08-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_workshop_divider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='date',
            field=models.DateField(blank=True, verbose_name='Date (YYYY-MM-DD)*'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='divider',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name="Add 'workshop-divider' (Unless it's the last workshop one on the page)*"),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='order',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name="Add'order-md-first' or 'order-md-last' accordingly*"),
        ),
    ]
