# Generated by Django 3.0.7 on 2020-08-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_auto_20200818_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='images',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='Image URL*'),
        ),
    ]
