# Generated by Django 3.0.7 on 2020-07-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20200728_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AddField(
            model_name='review',
            name='friendly_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
