# Generated by Django 3.0.7 on 2020-08-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200728_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='friendly_name',
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=45),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
